run:
  timeout: 5m
  build-tags:
    - e2e
    - mage

linters:
  disable-all: false
  presets:
    - bugs
    - unused
    - complexity
    - format
    - performance
    - style
  enable:
    - gci
  disable:
    - paralleltest
    - nlreturn
    - exhaustivestruct
    - wsl
    - godox
    - scopelint
    - maligned
    - interfacer
    - golint
    - exhaustruct
    - containedctx
    - depguard

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck
        - varnamelen

linters-settings:
  varnamelen:
    max-distance: 16
    min-name-length: 2

  gomoddirectives:
    # List of allowed `replace` directives. Default is empty.
    replace-allow-list:
      # FIXME: until github.com/cli/cli requires forked github.com/cli/shurcooL-graphql
      - github.com/shurcooL/graphql
